### ISSUE TITLE
mysql workbench and current glib

### ISSUE THREAD

**Issue by elgui02** [willysr/slackbuilds#3]
Hi willy, i just wanna tell you about mysql-workbench problem with slackware current, i ask you few week ago but the problem doesn't fixed, if you let me tell you the solutions is on glibmm i upgrade this librery to 2.44 version http://caesar.acc.umu.se/pub/gnome/sources/glibmm/2.44/glibmm-2.44.0.tar.xz

thanks :)

**Comment by willysr** [comment]
i already have that on my system :)
